sudo: required

language: php

cache: yarn

php:
- 7.1
- 7.2
- 7.3

notifications:
    email:
        on_success: change
        on_failure: always

before_script:
  - composer install --no-interaction --no-suggest --ignore-platform-reqs
  - nvm install node
  - npm install -g yarn
  - yarn
  - yarn run dev

script:
 - ./vendor/bin/phpunit
 - cat ./storage/logs/laravel.log

