sudo: required

language: php

php:
- 7.1
- 7.2
- 7.3

notifications:
    email:
        on_success: change
        on_failure: always

before_script:
  - composer install --no-interaction --no-suggest --ignore-platform-reqs

script:
 - ./vendor/bin/phpunit
 - cat ./storage/logs/laravel.log

