language: php

php:
  - '7.0'
  - '7.1'

before_script:
  - cp .env.testing .env
  - touch database/testing.sqlite
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit

sudo: false

services:
  - redis-server

cache:
  bundler: true
  directories:
  - node_modules # NPM packages
  - vendor

notifications:
    on_success: never
    on_failure: always