language: php
dist: trusty

php:
  - '7.0'
  - '7.1'

notifications:
    on_success: never
    on_failure: always

before_script:
  - phpenv config-rm xdebug.ini
  #  TODO
  #  - pecl install imagick
  - composer install --no-interaction --no-suggest --ignore-platform-reqs
  - nvm install node
  - npm install -g yarn
  - yarn
  - npm run dev -- --progress=false

script:
 - ./vendor/bin/phpunit
 - cat ./storage/logs/laravel.log

